apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deploy
  labels:
    app: http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server-zkyy66
        image: docker.io/zkyy66/http_serverv:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
